name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Load enviornment variables
      env:
        DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
        DB_CONNECT: ${{secrets.DB_CONNECT}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt