name: Python application

on:
  push:
    branches: 
    - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build

      with:
        python-version: 3.7
      env:
        DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
        DB_CONNECT: ${{secrets.DB_CONNECT}}

      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        docker build --tag suzy-bot .
        docker run suzy-bot
        